### ISSUE TITLE
corne-chocolate

### ISSUE THREAD

**Issue by AlexanderElias** [foostan/crkbd#1]
Awesome project exactly the design I have been looking for. Where might I find the design files for the corne-chocolate? Is it the classic?

**Comment by jeffreykxiao** [comment]
I don't think corne-chocolate has been created yet. About a month ago, @foostan added boilerplate for crkbd++ and crkbd+h (a next gen ckrbd and a hotswappable crkbd), but more recently, he renamed the original crkbd to ckrbd-classic and set up a new folder for crkbd-cherry. I think we'll see designs for crkbd-chocolate in the next month.

If you're interested in the crkbd that supports kailh choc, then the classic is your best bet at this moment. The classic doesn't have or support hot-swap, though.

**Comment by AlexanderElias** [comment]
Thanks @jeffreykxiao I appreciate the response. Looking forward to the chocolate @foostan thanks for the work. I think I will give the classic a try for now.

**Comment by foostan** [comment]
@jeffreykxiao Thank you for following me!
Corne-chocolate is still in development, I will release as soon as possible.

**Comment by AlexanderElias** [comment]
Well count me in on this follow fiesta!
