### ISSUE TITLE
./plates/common/*.svg files broken

### ISSUE THREAD

**Issue by ceceba223** [foostan/crkbd#107]
The .svg files for the plate are incomplete, meaning that the blue and red cut-lines aren't visible.
[Here](https://imgur.com/a/LXpfRNw) is a screenshot of the bottom.svg opend in Inkscape.
This is also an error with other .svg files in the repositorie.

**Comment by keyboard-magpie** [comment]
https://imgur.com/a/JcsbuDI

If viewed in a CAD program they are fully visible (this is QCAD on mac, freecad etc produce a similar view).

**Comment by ceceba223** [comment]
I tried opening the file in LibreCAD but got the same problem.

**Comment by keyboard-magpie** [comment]
I should prob do a PR with some working DXFs...

**Comment by ceceba223** [comment]
What DXFs there are only .svg and .ai files

**Comment by keyboard-magpie** [comment]
I have some I've made locally.

**Comment by keyboard-magpie** [comment]
https://github.com/keyboard-magpie/crkbd-plate-files

**Comment by criscol64** [comment]
> The .svg files for the plate are incomplete, meaning that the blue and red cut-lines aren't visible.
> [Here](https://imgur.com/a/LXpfRNw) is a screenshot of the bottom.svg opend in Inkscape.
> This is also an error with other .svg files in the repositorie.

The issue is the width of the lines, what I did was select all and then go to the properties of the lines and increase the witdh.

**Comment by foostan** [comment]
It seems good to change the width of line.

**Comment by medoix** [comment]
Adjusting the line width seems to not work for me in Inkscape. 
I get the following selection when selecting all.
Inkscape also shows the outlines when attempting to import the .AI file but then it does not import correctly.
Can someone upload/link a corrected SVG version?
![image](https://user-images.githubusercontent.com/149519/125184817-347ac480-e264-11eb-89bf-301f6af1a878.png)

**Comment by foostan** [comment]
Thank you your commitment! https://github.com/foostan/crkbd/pull/112
I'll close this issue.
