### ISSUE TITLE
Understanding the electronics

### ISSUE THREAD

**Issue by DLopezGo90** [foostan/crkbd#108]
Hi 

As far as I know both Pro Micro (left and right hand) communicate with each other using serial communication. For this I thought that RX from device 1 needed to be connected to TX from device 2 (and TX from device 1 to RX from device 2)

![image](https://user-images.githubusercontent.com/59780264/121465974-9786ec00-c984-11eb-8b96-ca013fda95f2.png)

But in Corne Keyboard electronic design I can see that the connection between both Pro Micro goes from pin RX of one of them to the pin RX of the other one (green line). I read that pin RX can only receive data but can't send. So how do both Pro Micro communicate with each other?

![image](https://user-images.githubusercontent.com/59780264/121465935-8807a300-c984-11eb-918b-870589907469.png)

Thanks in advance

**Comment by getarun** [comment]
Hello, stumbling across this - I would like to confirm for the actual .sch file, but cant' open project's .sch. 
Tried Kicad 5.1.5. and some online tools.

**Comment by foostan** [comment]
Split keyboard communication is implemented by QMK. There is no problem in actually connecting RX1s to each other.

**Comment by thmxv** [comment]
I had to search a bit through th QMK doc to actualy find the technical explication, which can be resumed to:

> Serial in this context should be read as sending information one bit at a time, rather than implementing UART/USART/RS485/RS232 standards.

Basically QMK uses one GPIO pin to transmit data serially using a dedicated protocol, and have nothing to do with "classic" UARTs except the unfortunate 'serial' name.

The link given by @foostan is to the source code and quite difficult to understand. Those pages in the documentation are much more helpfull:
https://docs.qmk.fm/#/feature_split_keyboard
https://docs.qmk.fm/#/serial_driver

**Comment by foostan** [comment]
I'll close it because it's not this project.
