### ISSUE TITLE
Right half fail with VIA firmware

### ISSUE THREAD

**Issue by ivanguardian** [foostan/crkbd#109]
Hi!!!
Could you help me to understand this case.

Right half, it does not work when I flash the pro micro with the firmware "VIA" , but it does works when I use one firmware generated from QMK

Left half
Pro Micro: red sparkfun
Firmeware: works with both (VIA,QMK)
Interface: USB C

Right half
Pro Micro: Pro Micro Black.
Firmware: works just with QMK.
Interface: micro USB.

firmware used:
QMK: crkbd_rev1_common_layout_split_3x6_3_mine.hex
VIA: crkbd_rev1_common_via.hex

![IMG_20210624_011613_535 1](https://user-images.githubusercontent.com/79780019/123219397-15212080-d48a-11eb-95b9-c9b10ad4c9cb.jpg)

**Comment by keyboard-magpie** [comment]
What exactly doesn't work?

No function at all with the black micro?

**Comment by ivanguardian** [comment]
> What exactly doesn't work?
> 
> No function at all with the black micro?

is like nor recognize the firme ware, and it

**Comment by ivanguardian** [comment]
> What exactly doesn't work?
> 
> No function at all with the black micro?

That's right, absolutly nothing work
Even it causes a windows error "Usb device not recognized"

So that's why I had to get a red pro micro, in order to test instead of the left side black pro micro. 
It turned out without a hitch.
![QMK_FlashingVia](https://user-images.githubusercontent.com/79780019/123490325-0db85f00-d5d1-11eb-9765-936e4ba8fcdb.png)
