### ISSUE TITLE
Kicad Gerber File Board outline not detected by JLCPCB 

### ISSUE THREAD

**Issue by BenRoe** [foostan/crkbd#11]
Hello,
i created the Gerber files wit KiCad and uploaded it to JLCPCB, but the outlines are not detected.
![bildschirmfoto 2018-12-12 um 18 52 05](https://user-images.githubusercontent.com/643834/49888640-ca95a680-fe3f-11e8-8c1f-b87223019348.png)
![bildschirmfoto 2018-12-12 um 18 52 43](https://user-images.githubusercontent.com/643834/49888785-26f8c600-fe40-11e8-8ffa-76f42af5f49a.png)

This are my settings.
![bildschirmfoto 2018-12-12 um 18 52 54](https://user-images.githubusercontent.com/643834/49888669-de410d00-fe3f-11e8-8e59-1481a8ba6014.png)
![bildschirmfoto 2018-12-12 um 18 53 27](https://user-images.githubusercontent.com/643834/49888686-e9943880-fe3f-11e8-9dfb-c344d95d6a85.png)

I tried different settings, but every time the same problem.
Any suggestions?

**Comment by foostan** [comment]
Can output correct gerbers with those settings.
What version are you using?

![image](https://user-images.githubusercontent.com/736191/50559476-eef7eb00-0d3a-11e9-94a9-db92fa4f4e76.png)

![image](https://user-images.githubusercontent.com/736191/50559459-a93b2280-0d3a-11e9-8b5e-f08524b2656c.png)

**Comment by BenRoe** [comment]
It works. Many thanks.
I use version 6.0.0-rc1-dev-1291

**Comment by fi0** [comment]
@BenRoe do you mind sharing the gerber files for crone classic please? I met similar issues on JLCPCB. thank you!

**Comment by Zeioth** [comment]
I'm also ordering from JLCPCB. What size should I indicate?
