### ISSUE TITLE
Type of PCB

### ISSUE THREAD

**Issue by luifer10** [foostan/crkbd#110]
Hi i'm new in all of this and i want to make my own PCB in a fabric, but they told me the thickness and the material somebody could help me with that?

And also i'm trying to understand which code is the correct one for v3 cherry cause i don´t know how to use kidcad. 
I don´t understand the documentation where i need to start for make a cotization for a pcb

**Comment by waymond91** [comment]
I think you're way better off posing this question to some electronics forums than here - the pro-micro used in the project is an atmega32u4 - so I would try on the arduino forum. Its super active.
Getting PCBs manufactured is also a good question for an electronics forum - not really a subject that can be covered comprehensively here. Maybe start with EEVBlog tutorials.

**Comment by foostan** [comment]
@luifer10 Basically, you can use 1.6mm PCB. If you want to change thickness you can use 1.0mm - 1.6mm. Thanks.
