### ISSUE TITLE
it seems there are solder mask openings missed in the file

### ISSUE THREAD

**Issue by stickpro** [foostan/crkbd#113]
Any can help me with this problem?
![image](https://user-images.githubusercontent.com/25886722/123923836-09ee5900-d992-11eb-8ebd-b4a0eb1722e9.png)

**Comment by keyboard-magpie** [comment]
That is normal for the top layer. As long as the solder mask openings are present on the bottom layer (underside) you can proceed.

**Comment by stickpro** [comment]
@keyboard-magpie  TY
