### ISSUE TITLE
Using mouse-key in VIA firmware

### ISSUE THREAD

**Issue by RyogaOTAKE** [foostan/crkbd#123]
I have set mouse keys in my keymap using VIA. However, it was not worked. Is it impossible to use mouse keys through VIA app?

**Comment by keyboard-magpie** [comment]
You will need to recompile the via firmware adding  `MOUSEKEY_ENABLE = yes` to the rules.mk file.

**Comment by RyogaOTAKE** [comment]
Thanks!

**Comment by foostan** [comment]
I'll consider turning on this option for default.

**Comment by jtr109** [comment]
> You will need to recompile the via firmware adding `MOUSEKEY_ENABLE = yes` to the rules.mk file.

To the newbie like me: This means you should download [the QMK firmware project](https://github.com/qmk/qmk_firmware) and change it in the [keyboards/crkbd/keymaps/via/rule.mk](https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/keymaps/via/rules.mk). Then, you should [flash it manually](https://github.com/foostan/crkbd/blob/main/doc/firmware_en.md#optional-if-you-build-the-firmware-yourself).

**Comment by kamaaina** [comment]
rev3 of PCB seems to be out, but QMK only shows rev1 and r2g... how would one compile for rev3?

**Comment by waffle87** [comment]
Yes, the `rev1` firmware in QMK is used for all versions of the DIY PCBs.
