### ISSUE TITLE
what are the keycaps in the photos for the chocolate switches?

### ISSUE THREAD

**Issue by pvinis** [foostan/crkbd#13]

**Comment by jeffreykxiao** [comment]
Designed by a user named `monksoffunk` on the Japanese Keyboard Discord

Link to product: https://make.dmm.com/item/1012817/

No idea if there's sale outside of Japan, maybe best to contact him. No idea about whether or not he speaks English.

**Comment by pvinis** [comment]
Thanks for the info. I'll see what I can do to get them! :)

**Comment by rjhilgefort** [comment]
@pvinis did you find these caps? Looking for them as well

**Comment by pvinis** [comment]
Last time I talked to (u/monksoffunk)[https://www.reddit.com/user/monksoffunk] and basically he sells (here)[https://make.dmm.com/item/1012817/] and he might sell (here)[https://25keys.booth.pm/] in the future for EU.

**Comment by rjhilgefort** [comment]
Cool, yeah, I just can't figure out how to order them even with google translate on. Thanks for the reply!

**Comment by pvinis** [comment]
I haven't tried yet. Maybe let's talk together and try to figure it out! Find me on anything else like twitter or discord, `pvinis` everywhere.

**Comment by rjhilgefort** [comment]
DM'd!

**Comment by IncognitoFawkes** [comment]
Were you guys able to figure out how to get the keycaps?
