### ISSUE TITLE
Larger M2 spacer hole on PCB to accomodate M2 Nylon Hex Type

### ISSUE THREAD

**Issue by saikocat** [foostan/crkbd#133]
Currently, the M2 spacer PCB hole can only accommodate brass type spacer (around 3.14mm diameter).

The nylon hex type (some people uses it for color coordination of black/white pcb/plate) like this one https://www.aliexpress.com/item/1005002263436936.html . This nylon spacer has 4.0mm diameter and can't go through the current hole size (4.3mm drill hole).

Even the Corne R2G edition has way larger hole for more spacer choices (https://groupbuys.mechboards.co.uk/wp-content/uploads/2021/07/HR2G_0000_20210603_112634.png).

Let me know where do you want to consolidate the discussion. Here or at https://github.com/foostan/crkbd/discussions/132

Cheers and thanks!

**Comment by foostan** [comment]
already fixed at v4
