### ISSUE TITLE
Incorrect labeling of LED order in Cherry v3 build guide.

### ISSUE THREAD

**Issue by gitgat** [foostan/crkbd#134]
The ordering of the LED's in the following images is incorrect in respects to the 1st LED and 8th LED on each half. Specifically the labeling for LED 1 and 8 should be switched, and LED 28 and 35 should be switched. The labeling was correct on my board from littlekeyboards.com. There is a chance i'm mis-reading the pcb files. 
- https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/assets/confirm_back.jpg
- https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/assets/build_diode_overview.jpg
- https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/assets/build_led_back_overview.jpg
- https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/assets/build_led_undergrow_overview.jpg
- https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/assets/build_led_back_overview.jpg

**Comment by foostan** [comment]
The builder does not need to be aware of the part numbers. This is the number used when manufacturing with PCBA etc. You don't have to worry because the number may be different depending on the version.
