### ISSUE TITLE
ambient LEDs (WS2812B) turn white on power on (Corne v3)

### ISSUE THREAD

**Issue by joric** [foostan/crkbd#144]
## Describe the issue

When I turn RGB off with an RGB toggle, the next power cycle (replugging the cable) turns the 6 ambient LEDs bright white. They can be turned off again by double RGB toggle but it's very annoying to do on each power on. Per-key LEDs are not affected.

## Expected behavior

Ambient LEDs supposed to stay off if RGB is disabled by the shortcut but they turn on.

## Hardware
Hardware is the original corne-cherry-v3.0.1 with 6 underside LEDs (WS2812B) and 21 per-key LEDs (SK6812MINI-E).

## Firmware
Firmware is the latest QMK, December 2021, default keymap (official builds including VIA builds are also affected).

## Additional info

* It looks like hardware issue because only WS2812 LEDs are affected, do I need decoupling caps there or something?
* I can't check if I have bad Pro Micro wifh a faulty/bad power circuit but it's a green one, I don't have another one.
* It also needs to set max brightness to 120 (it trips polifuse and hangs otherwise), stock firmware has that already.
* It may be unoriginal WS2812B LEDs I desoldered from an old RGB strip but they work fine except that one issue.
* It maybe can be fixed by turning LEDs off on startup but official firmware doesn't do that. Should we add that?

Related post on reddit: https://redd.it/p7dha4 both halves are affected so there's no random dry joints, it's rather QMK/LEDs.

**Comment by foostan** [comment]
@joric Please join the discord server https://discord.gg/SHVc2crgw8 and you can get support here.

**Comment by joric** [comment]
Oh I've been told they may be RGBW so I got to try adjusting the firmware to RGBW (or replacing them with RGB ones).

**Comment by joric** [comment]
I tried #define RGBW 1 in config.h and it didn't fix the issue on WS2812b's but it severely broke the colors on SK6812MINI's, so this is still open. I'll get better promicros next week and I'll try them maybe it has something to do with the green promicros power scheme/voltage drop or something.

**Comment by joric** [comment]
Nope, checked with Purple USB-C promicros, same behavior. Probably have to set them to black on init.

**Comment by joric** [comment]
OK I replaced the LED's. Looks like init is different for the different chips, these things are complicated. It works now.

Video:

[![](https://img.youtube.com/vi/tOkUNVnuroQ/maxresdefault.jpg)](https://youtu.be/tOkUNVnuroQ)


I desoldered the old ones from the old RGB strip:

Old LEDs: https://www.aliexpress.com/item/32808513592.html
New LEDs: https://www.aliexpress.com/item/32623583544.html

Rear side is also different:

![Untitled-1](https://user-images.githubusercontent.com/852547/149622270-3618d223-2ca9-4e62-abf1-36c99f32d8d4.jpg)
