### ISSUE TITLE
staggered pinky like kyria with kailh choc

### ISSUE THREAD

**Issue by rnyPlanet** [foostan/crkbd#145]
staggered pinky like kyria. it can turn out to take as a [basis](https://github.com/foostan/crkbd/blob/main/corne-light/doc/v2/buildguide_low_edition_en.md)?

will it be possible to use kailh choc without hot swap for [this keyboard](https://github.com/raychengy/fifi_split_keeb#fifi-keyboard--%EF%B8%8F) which is based on the crkbd (I would try to do it myself - but I have no knowledge) ?
![fifi_pcb_board](https://user-images.githubusercontent.com/33624178/146639375-508906d5-5764-44c5-bf10-03c88fc13801.png)

and can you explain what these holes are for?
![DeepinScreenshot_select-area_20211218132704](https://user-images.githubusercontent.com/33624178/146639439-5dc5734e-df47-4e7d-b5b8-4a12c9561c85.png)

@foostan maybe it won't take you long

**Comment by keyboard-magpie** [comment]
In your first picture, no, that will require redesign for choc specific sockets.

In your second picture, the 3 holes you have circled are for MX, Alps, and the rightmost is the extra leg for choc v2 switches.

**Comment by rnyPlanet** [comment]
> In your first picture, no, that will require redesign for choc specific sockets.

Is it possible, on the basis of the second board, to make a staggered for the pinky as in the first photo? (no sockets - to solder the switch to the board)

**Comment by keyboard-magpie** [comment]
It wouldn't be a crkbd then...

Its open source for a reason :) modify away.

**Comment by rnyPlanet** [comment]
> It wouldn't be a crkbd then...

I wore here because I like crkbd) but I would like a little improvement

> Its open source for a reason :) modify away.

I have no knowledge (

**Comment by keyboard-magpie** [comment]
I would invite you to come and talk on the low profile keyboards server, we have a #design channel [https://discord.gg/69UM9sQF8q](url)

**Comment by rnyPlanet** [comment]
> I would invite you to come and talk on the low profile keyboards server, we have a #design channel [https://discord.gg/69UM9sQF8q](url)

oh, interesting. I'll take a look)

**Comment by foostan** [comment]
@rnPlanet Thank you for sharing your design, I hole you challenge yourself to design your own 👍 
@keyboard-magpie Thank you for everything 🙏

**Comment by rnyPlanet** [comment]
> I hole you challenge yourself to design your own 

thanks😁  could you look with one eye and tell me if it will work?) https://github.com/pashutk/chocofi/pull/2, @keyboard-magpie or maybe you have knowledge)
