### ISSUE TITLE
SK6812MINI-E - No Caps/Resistors?

### ISSUE THREAD

**Issue by BeefcakeTheMighty** [foostan/crkbd#146]
I can't think of a way to phrase my question that doesn't sound critical so I'll preface this by saying that my question is **not** intended to be critical of your work. 

Why did you depart from the "typical application" illustrated on the data sheet by excluding the resistors and capacitors? 

Thanks in advance!

**Comment by BenRoe** [comment]
I have build a lot keyboards with SK6812 Mini-E and it worked without the capacitor, or resistors.

**Comment by BeefcakeTheMighty** [comment]
I'm not necessarily saying there should be a problem. I'm just looking for clarity about how this application differs from a "typical" application.

Or maybe the "typical" application recommends caps and resistors out of an abundance of caution??

**Comment by keyboard-magpie** [comment]
It's a balance between functionality and ease of building and component count. It works without them, absolutely fine, for years- so why add them if just to appease the data sheet writers?

**Comment by BeefcakeTheMighty** [comment]
Fair enough. Thanks for the guidance!!

**Comment by foostan** [comment]
On keyboards, I often see cases where the SK6812MINI-E is used without Caps or Resistors. Theoretically, it might be better to have them, but we use them because they have a proven track record.
