### ISSUE TITLE
Support KiCad 6

### ISSUE THREAD

**Issue by foostan** [foostan/crkbd#147]
The stable version of KiCad 6.0.0 was released. I'll update to support with all PCB data.
As far as I know, it will no longer be backward compatible with KiCad 5.
https://www.kicad.org/blog/2021/12/KiCad-6.0.0-Release/

TODO
- [ ] Corne Cherry
- [ ] Corne Chocolate
- [ ] Corne Classic
- [ ] Corne-light
- [x] https://github.com/foostan/kbd/issues/7

**Comment by joh** [comment]
Hi, any progress on this? :)
