### ISSUE TITLE
Keycaps on corne-chocolate

### ISSUE THREAD

**Issue by themmes** [foostan/crkbd#15]
Hey there!

I was wondering about the low profile keycaps on Corne Chocolate (photo 5 and 6). Were they custom printed? If so do you have the .STL files for those keycaps? If not, could you point me in the right direction to find some?

All the best,
Tom

**Comment by jeffreykxiao** [comment]
Might wanna check out #13 (resolved issue)

Also here's a specific link to the corne choc set as last time I posted the Helix set instead:
https://make.dmm.com/item/1009205/

**Comment by themmes** [comment]
Whoops embarassing, this is an exact duplicate. Thank you very much for your quick reply!
