### ISSUE TITLE
additional spacer holes to support 3x5 on Cherry PCB

### ISSUE THREAD

**Issue by dbldippy** [foostan/crkbd#150]
Feature request: Analog to the Choc PCB, add two spacer holes to the Cherry PCB that allows for a 3x5 form factor. The holes should be aligned with the existing mini plates

**Comment by dbldippy** [comment]
Another 5x3 enthusiast here. Would it be possible to also add the breakaway holes that the choc PCB has? Otherwise, I think the added holes are a bit pointless

**Comment by foostan** [comment]
https://github.com/foostan/crkbd/releases includes 3x5 suppoort
