### ISSUE TITLE
Question: Milling configuration for PCB production

### ISSUE THREAD

**Issue by DLFW** [foostan/crkbd#160]
Sorry for misusing the Issue tracking for a question, but I don't find an answer anywhere else.

For the tight cutout of the SK6812MINI-E footprint, what milling drill diameter is necessary for PCB production to have the LEDs fit into the cutout?

I saw that most PCB-manufacturers don't offer milling diameters below 1mm without extra costs. I guess that would not work with this footprint. What diameters have been used successfully?

BTW: PCB-production hints in the readme would be very helpful. :)

Thanks and thumbs up for the great board!

**Comment by foostan** [comment]
@DLFW  I have ordered PCBs from various factories and have never had a problem with LEDs. I have never seen any similar reports, so I don't think there is any problem.
