### ISSUE TITLE
No clear soldering order for LEDs for v3.0

### ISSUE THREAD

**Issue by geedmo** [foostan/crkbd#161]
As I read in many  build logs, it's recommended to test each led after solder each one in order to ensure there no problem because all are connected in serial. Because of that I think a picture with the sequence would be helpful.

**Comment by keyboard-magpie** [comment]
![F2E92327-2A2A-458F-AEBF-026F2E045857](https://user-images.githubusercontent.com/19674258/158043451-db43c130-b3c0-4f1c-8bfc-c121cfecb0cb.jpeg)

its the same order for all versions so far.

**Comment by geedmo** [comment]
Thanks. 
It was also mentioned in https://github.com/foostan/crkbd/issues/96 so I'm closing as duplicate.
