### ISSUE TITLE
Corne Cherry v3's build guide which describe micro B is hard to understand.

### ISSUE THREAD

**Issue by igsr5** [foostan/crkbd#162]
## Why

I am a beginner in self-made keyboards.
I recently purchased and assembled a kit of Corne Cherry v3.

But, when assembling micro B, I made a mistake with the parts 😢 

| correct | bad(in my case) |
| :---: | :---: |
| ![IMG_1741](https://user-images.githubusercontent.com/66525257/158048299-96ddd959-7f2d-4824-aa82-9e861f593e85.jpg) | ![IMG_1743](https://user-images.githubusercontent.com/66525257/158047810-38aa0c66-43b9-44b4-837b-32526ec8bd9f.png) |

This difference is very difficult to understand and is currently not well described in the documentation.
I want to make the documentation easy to understand for beginners like me.

## What
Please update Corne Cherry v3's build guide which describe micro B  for clarity.

**Comment by foostan** [comment]
The build guide of Cherry V3 EN is updated by @waffle87. Thank you for the feedback!
