### ISSUE TITLE
Number the LEDs on cherry silks in wiring order

### ISSUE THREAD

**Issue by grzes** [foostan/crkbd#166]
Seems like the first backlight LED after the last underglow is the outermost thumb cluster one and from there the strip "snakes" through the columns, but the silk print numbers the leds in rows instead. It would make troubleshooting easier if the labels matched the strip wiring order.

**Comment by agusdmb** [comment]
i soldered and soldered the LED 1 until i completely distroyed it waiting for it to turn on... i then realized the numbers were wrong :facepalm:

**Comment by artt** [comment]
That threw me off too until I found this: https://github.com/foostan/crkbd/issues/96

Maybe I'll add this to the build guide.

**Comment by foostan** [comment]
https://github.com/foostan/crkbd/releases uses matrix led and v4 is recommended PCBA so it doesn't care silk order.
