### ISSUE TITLE
firmware issues

### ISSUE THREAD

**Issue by LuckyFishGeek** [foostan/crkbd#170]
PCB: corne-cherry V3

After the crkbd_rev1_common_via.hex firmware is flashed into both the left and right ProMicro devices, only one side works at a time, the other keyboard does not work and the OLED does not display.

Specific demonstration

 https://youtu.be/5wZfeNqG4VE

**Comment by keyboard-magpie** [comment]
Pro Micro controllers have a hardware bug that causes this issue. 

You will need a QMK command line environment set up and working. 

You need to edit your keymap's config.h file to add `#define SPLIT_USB_DETECT` and recompile and reflash the firmware. 


Alternatively, you can flash this firmware which already has these changes made: https://qmk.tzarc.io/crkbd_r2g_via.hex

**Comment by psclwsr** [comment]
I tried using this firmware file, but the provlem still persists. I am using the ELITE-C controllers. The sides work on their own, only the one connected via TRRS doesnt.

**Comment by lexa2hk** [comment]
thanks! helped a lot

**Comment by TRIPSLORD** [comment]
> Pro Micro controllers have a hardware bug that causes this issue.
> 
> You will need a QMK command line environment set up and working.
> 
> You need to edit your keymap's config.h file to add `#define SPLIT_USB_DETECT` and recompile and reflash the firmware.
> 
> Alternatively, you can flash this firmware which already has these changes made: https://qmk.tzarc.io/crkbd_r2g_via.hex

The link is dead can anyone reupload?

**Comment by BlwAverage** [comment]
> > Pro Micro controllers have a hardware bug that causes this issue.
> > You will need a QMK command line environment set up and working.
> > You need to edit your keymap's config.h file to add `#define SPLIT_USB_DETECT` and recompile and reflash the firmware.
> > Alternatively, you can flash this firmware which already has these changes made: https://qmk.tzarc.io/crkbd_r2g_via.hex
> 
> The link is dead can anyone reupload?

If anyone else stumbles on this and needs it you can get my firmware file here https://github.com/BlwAverage/corne-kb-firmware
