### ISSUE TITLE
3x5

### ISSUE THREAD

**Issue by illmillrig** [foostan/crkbd#172]
can this pcb not have the ends snapped off to be 3x5 anymore?  any physical reason why you couldn't cut the pcb?

**Comment by waffle87** [comment]
Left half shouldn't be an issue if you were to cut down the middle.
![image](https://user-images.githubusercontent.com/59737601/169709558-16292732-bf07-49ec-a757-d108196e6521.png)
Right half, there's a data line for the underglow LEDs.
![image](https://user-images.githubusercontent.com/59737601/169709581-8e06944d-b19b-43d1-96d0-235d15a35f8b.png)
This wouldn't be an issue if you don't plan to use RGB, or you could just replace the connection with a jumper wire.

**Comment by illmillrig** [comment]
thank you.  I just scored it with a razor blade and snapped it like glass.  jumper wire worked perfectly.
