### ISSUE TITLE
JLCPCB preview not showing proper cutouts on Cherry board.

### ISSUE THREAD

**Issue by cam443** [foostan/crkbd#175]
I made some modifications to the board in KiCad and exported it as a gerber for JLCPCB. This is the preview image I get:
![Screenshot 2022-06-05 at 19-52-43 PCB Prototype - JLCPCB](https://user-images.githubusercontent.com/49173904/172087237-1e858761-7684-46d6-a972-666d7ae2e49f.png)

I also uploaded the corne-cherry-v3.0.1 gerber zip from the releases section and it has the same issue. Is this just an issue with the display of JLCPCB or an issue with the Edge layer of this specific board?

**Comment by keyboard-magpie** [comment]
This is quite normal, in my experience, and just a quirk of the JLCPCB gerber viewer.

**Comment by foostan** [comment]
As keyboard-magpie said, this is normal at JLCPCB.
