### ISSUE TITLE
mini corne case pcb gerber files?

### ISSUE THREAD

**Issue by SisadaR** [foostan/crkbd#176]
there only ai/svg version of the file.

is it possible for gerber version to be released?

**Comment by waffle87** [comment]
It wouldn't be too difficult to import the SVG to KiCad, and export gerber files yourself. 
[Importing Complex Board Outlines as Vector Graphics](https://community.element14.com/members-area/b/blog/posts/kicad-6---importing-complex-board-outlines-as-vector-graphics)
[Generate Gerbers](https://www.youtube.com/watch?v=ENmDnoKs2hM)
