### ISSUE TITLE
Violet keycaps from readme.md

### ISSUE THREAD

**Issue by BorkowskiDominik** [foostan/crkbd#178]
Hi!

Sorry for creating ticket for it but I really love those violet-rounded keycaps from readme file. I've been looking for similar for few days and can't find anything like them.

Can you please give me a hint where can I get ones?

By the way. 
Great keyboard! 
Thank you for your commitment! 

Regards, 
Dominik

![keycaps_corne](https://user-images.githubusercontent.com/44896053/180888632-2b97e1b4-13fe-40e7-869d-56687f4f26bd.png)

**Comment by foostan** [comment]
https://drop.com/buy/massdrop-x-mito-canvas-xda-custom-keycap-set

MITO XDA CANVAS Wolfgang
