### ISSUE TITLE
TRS Cable is Insufficient

### ISSUE THREAD

**Issue by cgrange** [foostan/crkbd#18]
The build guide says that TRS or TRRS cables can be used. I tried mine initially with a TRS cable and whatever side was plugged into the usb cable worked but the other would not. Once I replaced the TRS cable with a TRRS cable both halves worked perfectly. I could be the exception to the rule but I doubt it since most split keyboards require TRRS. I wonder if the build guides are wrong in stating that either TRS or TRRS cables will work.

**Comment by foostan** [comment]
The Crkbd can use TRS cable.

Please check kicad data.
![image](https://user-images.githubusercontent.com/736191/58818548-24e22800-8669-11e9-8a61-f007b279dde8.png)

**Comment by vxid** [comment]
I had the same issue as @cgrange. TRS did not work, TRRS did.

**Comment by gelpicr** [comment]
I actually had the same issue with my build, but I was able to get it running by plugging in the TRS cable then connecting both sides to USB. It's obviously not ideal, but i'm still waiting on my TRRS cable to come in the mail. Glad to know I wasn't the only one and that TRRS should fix my problem as well.

note: I'm using the cherry hotswap version rather than the classic corne if that makes any difference.

**Comment by tominabox1** [comment]
I have also tried using a TRS cable with no success - Power was provided but appeared to be no data.

**Comment by foostan** [comment]
How long your TRS cable?
I saw an issue where left and right communication fails when using a cable that is too long.

**Comment by tominabox1** [comment]
I'm using rev 1.1 boards if that has anything to do with it. The cable I
used is only 3 feet I think.

**Comment by foostan** [comment]
https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/serial.c#L137

Please try changing `SELECT_SOFT_SERIAL_SPEED` value.

**Comment by tominabox1** [comment]
Trying on my dual pro-micro board now and it is actually working with a short cable... I'll have to check on my other one!  I didn't change any config options.

**Comment by tominabox1** [comment]
Confirmed TRS works on both of my cornes without changing any settings. I believe I had a bad solder joint on the one board I was having issues with.

**Comment by foostan** [comment]
I’m glad working your corne. Thanks.

**Comment by BeaRRRRR** [comment]
I got my hotswap cherry corne working with a 3 meter TRS cable, so I think that cable length isn't really important.

**Comment by Brammm** [comment]
@cgrange did you ever get TRS working? I have a high quality Rode TRS cable but experiencing the same issue.

**Comment by vguerci** [comment]
After diagnosing a similar issue, I can confirm that `TRS` should work. Thus there is an issue that happens easily, if you short the TRRS Socket pads there: ![trrs-socket](https://i.imgur.com/pszblbt.png)

When A-D are shorted, this is not an issue with TRRS cables but is one with TRS cables that short B-D pads. VCC and data are then shorted.

I hope that helps.

**Comment by Brammm** [comment]
Hmm, I'm using a Corne Cherry PCB but with some slight modifications (among which to use RGB LEDs with legs that solder more easily) and on mine, those 4 connections of the TRRS jack are in one line... I'll get in touch with the dude that modified the PCB's.

**Comment by vguerci** [comment]
The Worldspawn's "easy LED" version I guess. This one short by design the A-D pads and cannot work with TRS cables.
