### ISSUE TITLE
Acrylic Upper Mid Plate Is Missing Space For Switch Teeth

### ISSUE THREAD

**Issue by alexmadeathing** [foostan/crkbd#182]
The [sandwiched upper mid acrylic plate](https://github.com/foostan/crkbd/blob/main/plates/cherry%2B/top-middle.ai) contains no space in the 14x14mm switch holes for the switch panel mount teeth to grip onto the FR4 top plate. So the switches may fall out, especially when removing keycaps.

I've hacked together an STL with some cutouts (Reviung plate shown below, but this applies to Corne too) which has enabled me to print my own upper mid plate, but sadly I don't have Illustrator, so can't submit a PR to correct the issue at source.

I'd like to suggest that something like the cutouts shown below is applied to the Corne upper mid plate, so that the switches can grip the FR4 correctly.

![image](https://user-images.githubusercontent.com/12872500/191789166-4131bfa4-8fbb-4f30-be32-b4d915a8bf1f.png)

**Comment by foostan** [comment]
I think your suggestion is correct, but I don't think middleware is needed for the FR4 sandswitch keyboard. The file you are referring to is not active. Thanks!
