### ISSUE TITLE
Support for Cherry MX Low Profile Switches?

### ISSUE THREAD

**Issue by Lokei1970** [foostan/crkbd#186]
I read the documentations but didn't find the specific details about whether any of the models support Cherry MX Low Profile Switches:
https://www.cherrymx.de/en/cherry-mx/mx-original/mx-speed-silver.html
https://www.cherrymx.de/en/cherry-mx/mx-low-profile/mx-low-profile-red.html

Does any of the models support these types of switches?

**Comment by keyboard-magpie** [comment]
No. The latest revision of Corne Light supports Kailh Choc v2 which are the next closest thing to Cherry MXLP.

**Comment by Lokei1970** [comment]
@keyboard-magpie Thanks for the reply bro!

**Comment by adaviloper** [comment]
> No. The latest revision of Corne Light supports Kailh Choc v2 which are the next closest thing to Cherry MXLP.

Is the Corne Light or any of the other Kailh Choc boards set with MX spacing? I couldn't find if this was the case.
As in, are the Choc PCBs the exact same physical dimensions as the MX PCBs, except the footprints for the switches are replaced with Choc footprints?
I want to build a new low-profile Corne, but I prefer MX spacing.
