### ISSUE TITLE
Corne Classic v2.0 OLED Power?

### ISSUE THREAD

**Issue by taylorcoffelt** [foostan/crkbd#19]
I have the v2.0 boards of the Corne Classic, and I can't seem to get the VCC pin for the OLED to have power. 
I have the top OLED jumpers soldered on both sides. I'm currently using the Elite-C, and the test keypresses do work. Following the traces on the board, KiCad design, and schematic, it _should_ have power. 
 Anyone else have this issue?

**Comment by foostan** [comment]
> I have the top OLED jumpers soldered on both sides

Maybe it's mistake. You should solder one side. 
Please check [buildguide](https://github.com/foostan/crkbd/blob/master/corne-classic/doc/buildguide_en.md#jumpers-for-oled-modules-optional).

**Comment by taylorcoffelt** [comment]
My apologies, I was unclear in that statement.
I have soldered the OLED Jumpers on the top side of the PCB for both left and right boards, according to the instructions in the buildguide. I'm not seeing anything that is different in my setup, besides the fact that the buildguide is for v1.1 of the board, and mine is v2.0

**Comment by foostan** [comment]
> Anyone else have this issue?

No, I have not see this issue.
Please show me your assembly.
