### ISSUE TITLE
Use second USB-C as port for other devices

### ISSUE THREAD

**Issue by fureunoir** [foostan/crkbd#190]
There are two USB-C ports on the keyboard. One on each half. One is used to connect the board to the PC and another one is free. Is it somehow possible to use the free one to connect any other devices like flash drives or phone charger?

**Comment by waffle87** [comment]
Not without extensive hardware and firmware modifications. The "easiest" approach would be implementing a USB hub. The Drop keyboards are an example of this.

**Comment by wxz-site** [comment]
you can use this link to search and download "crkbd_r2g_via.hex" with new firmware to 2-type-c Pro Mircro ，can be fix it. 
https://www.caniusevia.com/docs/download_firmware#0
