### ISSUE TITLE
Question about v2 to v3 pcb schematic

### ISSUE THREAD

**Issue by D-Town44** [foostan/crkbd#194]
Hello!

I was looking at the PCB designs between the cherry corne v2 and v3, I noticed that v2 had a single double sided PCB (i.e. the same PCB for the left and right side). In v3, there are different PCB designs between the sides (i.e. a left side PCB can't be used as a right side PCB). 

I was just curious as to why that change was made. I imagine it is a lot easier to read and edit the individual single sides. I also imagine it is more expensive to manufacture the individual single sides (especially because the v3 designs have more break away/throw away PCB.

**Comment by foostan** [comment]
The circuit and footprints are simple, and changes have been made in v3 to make it easier to build. The manufacturing cost was not considered significant compared to its advantages.
