### ISSUE TITLE
Buy

### ISSUE THREAD

**Issue by kamalkech** [foostan/crkbd#196]
How can i buy this keyboard without bluid it from scratch ??

**Comment by keyboard-magpie** [comment]
Find a vendor like mechboards.co.uk that offers an assembly service.

**Comment by kamalkech** [comment]
@keyboard-magpie thank u for answer + help and i am sorry if i post the question on list of tasks hhhh it s funny, because i have not a way to contact with u, from this site can u recommend the best of keyboard corne rgb ?? thank u soo much.

**Comment by foostan** [comment]
We can communicate at https://discord.gg/aWCZWnS, thanks 🙏
