### ISSUE TITLE
Default key mapping not adding normal :

### ISSUE THREAD

**Issue by oanaOM** [foostan/crkbd#197]
Hi,

I recently build a corne v3 chocolate split keyboard, downloaded the firmwire from your docs: https://raw.githubusercontent.com/foostan/qmk_firmware-hex/main/.build/crkbd_rev1_via.hex and when I type SHIFT + ; I get `+` instead of `:` as expected. I can't seem to change this via QMK configurator or Via. Do you know why this could happen?
Does this mean I need to configure my own firmwire?

Thanks! 
Oana

**Comment by foostan** [comment]
Sorry for the late reply. I don't know the details, but it is odd that you can't change it via. If you still haven't resolved it, ask on [discord](https://discord.gg/2TEDnJE8).
