### ISSUE TITLE
Corne cherry v3 into mini

### ISSUE THREAD

**Issue by driccio** [foostan/crkbd#198]
Hi,

I have pcbs for corne cherry v3. I wonder if the pcb can be cut to have only 5 columns as nothing help to cut it (unlike the corne choco for instance).

Thanks for your answer.

Damien

**Comment by foostan** [comment]
v3 doesn't support the mini version.

**Comment by driccio** [comment]
Hi foostan, 

Thanks for your answer. Even if not supported with pre-cut pcb, I thought it was possible to cut it with precautions in order to have a mini version. I understand by your answer there is no way.

**Comment by driccio** [comment]
Hi,

To answer myself, here is how I cut the PCB of a cherry v3 in order to have a mini version.

**Disclaimer** : I am not an expert and I just share what I did in order to help.

**What you need to know before ?**
If you don't have LEDs, then you have nothing else to do than cutting the PCB.
If you have LEDs, then you will break the LEDs circuit on the right hand. But it is easy to solve.

**Where should we cut the PCB ?**
Please see purple lines 1 and 2 that materialize the cutting line. 

![Capture d’écran du 2023-06-28 20-58-20](https://github.com/foostan/crkbd/assets/557200/fb617208-1fa0-43e2-8d03-2f1c7a88bd0a)


**How to cut the PCB ?**
Take a cutter and begin slowly to mark the line on both side of the PCB. Repeat operation in order to have deep lines that would allow you to break the PCB. Be careful !

![20230628_184112](https://github.com/foostan/crkbd/assets/557200/0ffd7211-607a-48e3-859f-d7537929e9ea)


**How to fix right hand ?**
I repair the break by connecting 2 LED with a piece of cable as you can see here :

![20230628_204531](https://github.com/foostan/crkbd/assets/557200/d56a6bac-1cbd-4da8-8e03-5f7092a8435b)


Result :-)

![20230628_191632](https://github.com/foostan/crkbd/assets/557200/ab299087-e01a-41cd-a608-f73ab37d42a3)


Enjoy

Damien
