### ISSUE TITLE
Available pins for a handwired encoder

### ISSUE THREAD

**Issue by jhelvy** [foostan/crkbd#199]
Hi, I'm trying to put an encoder on my corne, but I don't know which pins on the controller are available. I can't find a map - do you which ones I could use to solder the encoder leads to?

**Comment by waffle87** [comment]
B4, B5, B2, B6
![unknown](https://github.com/foostan/crkbd/assets/59737601/9255b61a-25b9-40b4-8e45-dc2843021737)

**Comment by jhelvy** [comment]
🙏
