### ISSUE TITLE
corne_light_2.0_alps-switchplate

### ISSUE THREAD

**Issue by SanoUsen** [foostan/crkbd#203]
Hi Mate!!
i dont know if im doing it wrong or just dump^^ but if im transfer the alps-switchplate.svg to .dxf it seem that the holes for the standoffs and Switches are not aligned. (i have printed it on paper and laid over the pcb)
Is there a chance to get a updated version if its wrong in the format dxf ?

best greets

**Comment by foostan** [comment]
Please check the size in svg before converting to dxf. If it was wrong in svg, we will accept a PR.
