### ISSUE TITLE
Mouse key doesn't work on corne keyboard with VIA

### ISSUE THREAD

**Issue by jittapont** [foostan/crkbd#206]
I checked the mouse key in the info.json and found that the mouse key is enabled. After configuring the mouse key in VIA. the mouse key didn't work mouse button 1 didn't do anything (I saw the keycode `K209`)

**Comment by foostan** [comment]
Sorry for the late reply. I don't know the details, but it is odd that you can't change it via. If you still haven't resolved it, ask on [discord](https://discord.gg/2TEDnJE8).
