### ISSUE TITLE
v4 questions

### ISSUE THREAD

**Issue by kuritonasu** [foostan/crkbd#212]
First things first, thanks for your awesome work foostan, I've been using my wireless Corne for almost a year now and I love every bit of its design and simplicity! It's my first ortho, first split keyboard and your design motivated me to solder and build it myself from scratch, even though I never soldered SMDs before.

I love the unified look of the v4, but I have a few questions regarding it, apologies if I missed any docs that answer them:

1. Does the v4 support wireless? I guess, firstly does it support a battery? And if yes, I guess the best place for it is where the two new keys are?
2. Secondly, ZMK & RP2040 don't support split wireless keyboards yet if I'm not mistaken, right?
3. Which PCB manufacturer are you using? Do you assemble the board yourself or choose to have the boards assembled?
4. Is it possible to solder the v4 with a soldering iron, or am I right to think that it would be very difficult, especially for parts like the RP2040?
5. Are the "v4 Soldering" versions close to release? No pressure!
6. Judging from the design, you are releasing the v4 only with a non removable RP2040, right? No plans for a removable MCU.

Thanks again, keep up the good work!
![original_d83fb799-f692-40f0-9961-e35fb0f92836_20230515_170753-1](https://github.com/foostan/crkbd/assets/33165903/b6b83241-9574-45fb-85ab-91cde66a1052)

**Comment by KacperNapierski** [comment]
Also will it be possible for new version to be both wireless and wired, as with previous version it wasn't recommended due to way TRRS provided power to other half while battery was built in .

**Comment by keyboard-magpie** [comment]
The V4 PCB Foostan has published is wired only due to its on-board microcontroller.

**Comment by kuritonasu** [comment]
> The V4 PCB Foostan has published is wired only due to its on-board microcontroller.

Doesn't the RP2040 support wireless? Or does that require components on the microcontroller's board/shield (which is not part of this design)?

**Comment by keyboard-magpie** [comment]
The RP2040 on its own is not a wireless microcontroller. Boards like the Pi Pico W have a separate wireless module.

**Comment by keyboard-magpie** [comment]
Furthermore to your original points, the v4 will not be hand assembly friendly, unless you have EXTENSIVE reflow soldering experience.

**Comment by kuritonasu** [comment]
Thank you for the clarifications 🙏

**Comment by foostan** [comment]
> 1. Does the v4 support wireless? I guess, firstly does it support a battery? And if yes, I guess the best place for it is where the two new keys are?

Wireless is not supported. There are no plans to support it in the future. In Japan, there are strict laws regarding wireless, and it is not possible to use the module freely. Since this is an open-source project, I hope that some people will use it as a basis for the wireless version, as was the v3.

> 3. Which PCB manufacturer are you using? Do you assemble the board yourself or choose to have the boards assembled?

Files for the JLCPCB we be available

> 4. Is it possible to solder the v4 with a soldering iron, or am I right to think that it would be very difficult, especially for parts like the RP2040?

Basically, I expect to do PCBA.

> 5. Are the "v4 Soldering" versions close to release? No pressure!

I'll create after release v4.

> 6. Judging from the design, you are releasing the v4 only with a non removable RP2040, right? No plans for a removable MCU.f

Yes. There is no plan for a removable MCU.

**Comment by WillPower3309** [comment]
Will 3x5 cases be added?

**Comment by foostan** [comment]
I plan to create the case for 3x5

**Comment by 0n3W4y7ick3t** [comment]
can I use the case for v3?

**Comment by foostan** [comment]
No, v4 is not compatible v3

**Comment by foostan** [comment]
I'll close this issue. If you have any question and concern, please create a new issue.
