### ISSUE TITLE
four switches on the pcb of the left hand not working

### ISSUE THREAD

**Issue by OneCrazyman** [foostan/crkbd#213]
I am making a keyboard called corne v3 cherry.

After attaching diode and produino, short circuit all switch parts directly. Left and right both work well, but the four switches on the pcb of the left hand not working. When seen with the naked eye, all are soldered.

![화면 캡처 2024-03-07 022635](https://github.com/foostan/crkbd/assets/98089603/52b37878-5d88-41a4-857e-225bb7a4baf2)
![화면 캡처 2024-03-07 022702](https://github.com/foostan/crkbd/assets/98089603/5a03c40a-c2c8-4a4a-8712-fd78f7886382)

**Comment by OneCrazyman** [comment]
![Uploading KakaoTalk_20240307_023304217.jpg…]()

**Comment by foostan** [comment]
The problem with one vertical row not moving is in the connection with ProMicro. Try re-soldering it cleanly.

**Comment by foostan** [comment]
I'll close it because this issue is not related to design. If you have any concerns please continue at Discord https://discord.gg/aWCZWnS
