### ISSUE TITLE
Corne Cherry v2 detailed manual needed

### ISSUE THREAD

**Issue by set-st** [foostan/crkbd#220]
Is any v2 flashing manual exist? I trying found instructions about enabling oled displays. Of course im add `#define USE_I2C` and separate halfs is working well, but then i try connect it by wire and screens not works, and on right side nothing works exept backlight. And will be exelent to be got some details about resistors and jumper to data pin which detached by default.

**Comment by foostan** [comment]
- Where did you get the PCB? 
- Did you build firmware yourself? (Normally you don't need to change anything) 
- Is the cables broken?

**Comment by set-st** [comment]
I found short cut on one of i2c pin and data, so it can't work properly. Now i order official pcb.

**Comment by foostan** [comment]
It will be closed as there have been no comments for some time. Reopen if necessary.
