### ISSUE TITLE
How to order plates?

### ISSUE THREAD

**Issue by rydeom** [foostan/crkbd#222]
Hey, I am pretty new to ordering PCBs and stuff. I want to build a Corne V4 with Kailh Choc V1 switches. Which of the plates do I need to order? The Alps, Cherry or none of the above? 
When I upload the gerber files for the cherry top plates to jlcpcb it looks like this: 
<img width="973" alt="Bildschirmfoto 2024-03-28 um 21 44 08" src="https://github.com/foostan/crkbd/assets/30581153/225f90aa-e378-4dd4-9f39-ddff520fc69c">
And the Gerber file view like this:
<img width="1302" alt="Bildschirmfoto 2024-03-28 um 21 44 25" src="https://github.com/foostan/crkbd/assets/30581153/cf04c31f-1cc8-44a7-a1cd-81bb2782c07f">

Is this how it should be?

**Comment by foostan** [comment]
Please chose the cherry plate for choc (same plate). And your screenshot looks normal so no problem.
