### ISSUE TITLE
V4 Cherry build question

### ISSUE THREAD

**Issue by jaeheonji** [foostan/crkbd#223]
Hi, I received the following request from JLCPCB while ordering the v4 version (cherry), but I do not know anything about it, so I am asking a question.

![image](https://github.com/foostan/crkbd/assets/32578710/acd06f44-b296-45aa-9e9c-519a5ed3a395)

Above image, the indicated pad and trace is connected. Should I need to separate them?

**Comment by foostan** [comment]
It's no problem. 
I think it would be best for you to confirm the data with kicad before ordering to the factory.
![image](https://github.com/foostan/crkbd/assets/736191/d738c311-4f13-4b3b-b320-5bccb76ce01d)

**Comment by foostan** [comment]
I have fixed this just in case. Thanks

**Comment by jaeheonji** [comment]
Thank you so much @foostan !
