### ISSUE TITLE
[5 Column / minidox / broken off pcb] Case not compatible / no case files

### ISSUE THREAD

**Issue by ThomasMeulendijks** [foostan/crkbd#23]
The case files in the repo are only for the normal layout not for the 5 Column layout / broken off layout. 

Did anyone design a case for this? If so could you please share?
If not can anyone help me adapt it to fit the smaller form factor.

Greetings

**Comment by foostan** [comment]
> Did anyone design a case for this? 

No. We want a plate that for 5 column, I will make it.

**Comment by ThomasMeulendijks** [comment]
cool, thank you. I tried making my own if you want I can make a pull request

**Comment by foostan** [comment]
Thank you!
