### ISSUE TITLE
How to order? / Wrong parts placement when ordering from jlcpcb

### ISSUE THREAD

**Issue by MaxWinterstein** [foostan/crkbd#231]
Love your work, and currently typing this on an old corne <3

I tried to upload the files to jlcpcb but somehow the parts are mostly wrong rotated or misplaced. This happens for both cherry as well as choc. E.g. USB port is floating.

![image](https://github.com/foostan/crkbd/assets/5927148/c5897e1e-c538-4611-99fb-eb01b2796916)

![image](https://github.com/foostan/crkbd/assets/5927148/a21a40e6-496d-44fb-bdc2-252284c3ef7f)

There are others on Reddit having this issue too: https://www.reddit.com/r/crkbd/comments/1budyel/comment/kxuc1wx/

Thanks!

**Comment by foostan** [comment]
I answered the same question on my server 
https://discord.com/channels/715899960327012423/742781449731702824/1225199804477472858

> I don't know the details, but it may be a compatibility issue between the jlcpcb system and the data generated by kicad. The jlcpcb engineers will check and adjust the data, so there is no problem with the way it is.

**Comment by MaxWinterstein** [comment]
Thanks, will try to get them to adjust the data.

Sadly, the headphone jack is not in stock, probplaby since a few days already. Do you know any compatible alternative?

**Comment by foostan** [comment]
There is no alternative. If you want to change, you need to change the footprint. I'm waiting to be stocked.

**Comment by RodolfoBar** [comment]
In my case the engineer is asking me to confirm the placement of the parts. So I was thinking, would it be easier to have a diagram in the documentation/build guide that has the correct placement of the parts so that you can maybe avoid these questions in the future?

**Comment by RodolfoBar** [comment]
I'm having a similar issue with JLCPCB. I was wondering if there was any way that I could confirm the orientation and placement of the parts. I realise this might be a bit of a request, however the images that are on the README.md in the root are quite low resolution and I don't have that much knowledge with circuitry to really understand it. Thank you!

**Comment by Xartos** [comment]
I'm currently looking at creating a fork that uses [PJ-606-6A](https://jlcpcb.com/partdetail/Korean_HropartsElec-PJ_6066A/C145806) as the audio jack instead. However since @foostan wrote that there's no alternative I'm wondering if there's anything that I'm missing with it that makes it incompatible, of if that was meant that there's no alternative with the same pinout. Because other than the pinout they seem to have similar footprint so only minimal changes to the pcb is required.

**Comment by foostan** [comment]
I released https://github.com/foostan/crkbd/releases/tag/v4.1 for the connector issue.

**Comment by MaxWinterstein** [comment]
Thanks, I was able to order 4.1 from jlcpcb. They placed all parts correctly - but IIRC I checked and payed all boxes that involved production file verification and confirmation.

![image](https://github.com/foostan/crkbd/assets/5927148/41b0058b-d47d-4c6b-92e9-f7a86d437a26)

New connector works fine, currently typing on a v4.1. Thanks for the awesome work!

![image](https://github.com/foostan/crkbd/assets/5927148/8c22f4a9-0504-45bf-9c82-2324b834bab9)

Just had do use white switch holders, the black ones where out of stock at that moment.

**Comment by kijewskimateusz** [comment]
Thanks for great discussion there. When ordering my pcb, I have also been asked whether polarities of the components C5149201 are correct or not. (SMD-LED)

Could you please help me understanding if it is correctly applied by the JLCPCB team? Bellow I'm attaching render shared by the team. 
![7898919936-Produce_DanZhi SMT_Snapshot Bottom 7906916A_Y14 SMT02406011770433](https://github.com/foostan/crkbd/assets/65126185/352d8c66-289f-4a9a-93ba-c71df8539bd6)

**Comment by MaxWinterstein** [comment]
@kijewskimateusz 

Attached the file I accepted for comparison.

![17541230592-Produce_DanZhi SMT_Snapshot Bottom 4963460A_Y5 SMT02405151744340](https://github.com/foostan/crkbd/assets/5927148/93dfc0d4-d469-4af5-bc45-00236e365356)


Even I made MX style, and yours is choc, it can be compared. By looking at the LEDs it looks good to me, as the little triangle needs to be in the marked corner. The real LEDs have some little cutout.

![image](https://github.com/foostan/crkbd/assets/5927148/75d608b8-1021-4f5d-b003-c6addbb4eaf0)

**Comment by giograno** [comment]
Hei @MaxWinterstein, I am also trying to order the v4.1 with jlcpcb. The sockets and the trrs connectors are rotated/misplaced. As far as I understood, in your case jlcpcb itself managed to correct them, right?

**Comment by mhanberg** [comment]
@kijewskimateusz I am facing a similar issue with JLCPCB.

My switches in the mockup they sent look like yours, but i'm wondering, are they upside down? Did you end up getting assembled board and confirmed that that is correct?
