### ISSUE TITLE
Where are the rest of the board designs?

### ISSUE THREAD

**Issue by Koltsz** [foostan/crkbd#234]
Hi,

how can i get a hold of Corne Light v2 Low edition PCB? I can't seem to find it anywhere, can only find choc and mx cheery ones

**Comment by SparrowMike** [comment]
Not sure what exactly you mean.

But if you're after just the pcb here is one 

https://www.etsy.com/sg-en/listing/1113750577/corne-light-v2-pcb?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=corner+light&ref=sr_gallery-1-2&content_source=c3da52396f7fdb4c7e623868bcf19554bf095be1%253A1113750577&organic_search_click=1

**Comment by Koltsz** [comment]
> Not sure what exactly you mean.
> 
> But if you're after just the pcb here is one 
> 
> https://www.etsy.com/sg-en/listing/1113750577/corne-light-v2-pcb?ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery&ga_search_query=corner+light&ref=sr_gallery-1-2&content_source=c3da52396f7fdb4c7e623868bcf19554bf095be1%253A1113750577&organic_search_click=1
> 
> You could also find ultra light / light designs here https://github.com/petejohanson/crkbd/tree/board/corne-ultralight

Thanks for this,

I'm looking for the PCB files so I can get the PCB printed myself

**Comment by djw33** [comment]
There are different tags for each of the different versions. Is that what you're talking about:

![image](https://github.com/foostan/crkbd/assets/33916231/050909b2-8a54-417e-bbb4-221b8653ef2f)

**Comment by foostan** [comment]
Thank you for answering. You can find it by changing other tags.

**Comment by foostan** [comment]
I'll close this issue because it looks already solved.
