### ISSUE TITLE
V4.0 pcb usability for 3x5

### ISSUE THREAD

**Issue by threeonefour** [foostan/crkbd#240]
If I understand the fixes from 4.0 to 4.1 correctly, I should refrain from shortening my 4.0 pcbs to 3x5? Will this inevitably render the pcb functionless, or is there a workaround?

**Comment by foostan** [comment]
Please do not use 3x5 in v4.0, the PCB will be unusable. There is no workaround.

**Comment by threeonefour** [comment]
Ok, thank you for the quick clarification!
