### ISSUE TITLE
Killed the rPi by first time powering up with connected TRS cable?

### ISSUE THREAD

**Issue by MaxWinterstein** [foostan/crkbd#243]
I ordered 5 PCB pairs. 4 Work great, but 1 is missing any signs of life.

When I tested them, I accidentally powered one factory new PCB pair with a connected TRS cable. Is it possible to fry the chip when doing this? Like a brand new chip contains some firmware that has voltage where there shouldn't be any?

**Comment by gpmontt** [comment]
Maybe you need to secure the TRS cable. Some diodes can be helpfully here

**Comment by defekkt** [comment]
had the same issue, might have been a voltage spike when connecting TVRS cable *after* connecting USB.
turned out it killed the V-USB-> 5V Diode. might be worth checking for you too ;-)

**Comment by MaxWinterstein** [comment]
@defekkt can you give me more information on that? Not sure where this diode is, and how to check it. Thx :)

**Comment by defekkt** [comment]
1.grab a multimeter, put it in diode mode
2. on a known-working/good board/diode measure the diode in both directions
3. then check it on the faulty board, compare the values (should be different depending on the direction).

here is the diode, next to the usb-connector 
![corne_vusb_diode](https://github.com/foostan/crkbd/assets/6408494/bb14f0ab-d2e6-4bf8-b577-5fd54f68c9be)
