### ISSUE TITLE
Misaligned components on JCLPCB for Corne v4.1

### ISSUE THREAD

**Issue by cyuanli** [foostan/crkbd#252]
When uploading the production files for Corne v4.1 on JCLPCB, some components appear to be misaligned or rotated the wrong way.

**Cherry**
![corne-cherry](https://github.com/foostan/crkbd/assets/23528033/84215f16-c31e-4ec1-b7c1-abac3047a8c9)

**Chocolate**
![corne-chocolate](https://github.com/foostan/crkbd/assets/23528033/95a64c80-0a59-4ca2-962a-dec095178ca9)

Is this an issue on JCLPCB's side or should this be fixed in the files?

**Comment by foostan** [comment]
this an issue on JCLPCB's side

**Comment by Beato99** [comment]
JLCPCB Engineers will fix it for you before manufacturing, you can upload it like that

**Comment by cyuanli** [comment]
I received a message:

> Since we are not so sure about the polarities of the components C5149201 are correct or not. Could you please kindly check if the polarities and placements of the components are correct in the below picture? Is it okay to proceed with production?

![46408513536-Produce_DanZhi SMT_Snapshot Bottom 5503634A_Y6 SMT02407041822648](https://github.com/foostan/crkbd/assets/23528033/ac69db5f-57af-4ebb-81cf-57266ca9b457)

I couldn't find any indications in the documentation, does that seem correct?

**Comment by foostan** [comment]
It looks correct. I think this has already been discussed a few times on Discord.

**Comment by cyuanli** [comment]
Ah, I didn't think of checking the Discord, will do so in the future. Thanks a lot for the support, it's much appreciated!
