### ISSUE TITLE
Corne v4.1 3x5 Chocolate

### ISSUE THREAD

**Issue by noagbmn** [foostan/crkbd#253]
I'm pretty new to custom keyboards and PCB design, and I'm looking to order a 3x5 Choc keyboard PCB from NextPCB, as JLCPCB doesn't offer PCBA services in my region. (NextPCB requires a slightly different BOM format and component placement in Gerber format)

Do I understand correctly that I need to order 3x6 PCB and then cut it? And where exactly would I need to cut it?

**Comment by raphaelmor** [comment]
Hello, just received my 4.1 pcbs and will do a 3x5 with one of them. 

This parts snaps off to make the 3x5:
<img width="1060" alt="Screenshot 2024-07-10 at 16 59 06" src="https://github.com/foostan/crkbd/assets/772779/40a65aa6-f827-4cc9-b710-25d7e476fa2a">
