### ISSUE TITLE
Is it possible to make it wireless?

### ISSUE THREAD

**Issue by afrianjunior** [foostan/crkbd#255]
I want to upgrade my keyboard to wireless, is it possible?

**Comment by keyboard-magpie** [comment]
No. The rp2040 chip on board rev 4 does not allow this.

If you want a wireless crkbd, your best option is to get a revision 3 PCB and build it with wireless controllers such as nice!nanos or superminis.

**Comment by afrianjunior** [comment]
Thanks to clarify, Magpie.
