### ISSUE TITLE
How to map the extra 4 keys from rev4 using QMK ?

### ISSUE THREAD

**Issue by luc-vocab** [foostan/crkbd#257]
I am looking at the merge request to add crkbd v4 to QMK here : https://github.com/qmk/qmk_firmware/pull/24084
but it's not clear to me how the extra 4 keys can be mapped, how is it possible using the LAYOUT_split_3x6_3 macro ? Is there a sample somewhere ?

**Comment by luc-vocab** [comment]
For the layout macro, we have to use `LAYOUT_split_3x6_3_ex2`
I received a pre-assembled crkbd 4.1 which works fine with the default firmware from https://github.com/foostan/crkbd/blob/main/docs/firmware/rev4/firmware_en.md.
however when I build my own firmware with the above qmk pull request using `qmk compile -kb crkbd/rev4 -km via`, only one half works at a time. Does anyone have any suggestions on troubleshooting steps I could try ?

**Comment by foostan** [comment]
Have you checked https://github.com/foostan/kbd_firmware?

**Comment by luc-vocab** [comment]
@foostan I am trying right now, will report back very soon
