### ISSUE TITLE
Errors with the CPL

### ISSUE THREAD

**Issue by marleydepew** [foostan/crkbd#262]
When I upload the cherry BOM and CPL files to JLCPCB, there is an error message that they don't match. There are some differences with the hot swap sockets between the two files but even after removing those I'm still getting the error messages. 

![Screenshot 2024-09-11 074806](https://github.com/user-attachments/assets/4a622c84-30c3-477e-9518-4a4b10448011)

If you go to the next screen a number of the components are either in the wrong place or have the wrong orientation. For example the USB and TRS jacks are not connected to the PCB.  The components at U2, U3 and U4 are obviously not oriented correctly. I'm not sure if the remaining components are oriented correctly or not.

**Comment by sadtab** [comment]
Same here

**Comment by foostan** [comment]
I found the cause.
It seems that JLCPCB returns an error if lowercase letters are used in Designator.
For example, if I change `rU1` to `RU1`, no error occurs.
However, even if an error occurs, JLCPCB seems to process it correctly, so it looks like a warning is just being issued. It just seems like a bug.

**Comment by marleydepew** [comment]
When you tried it on your end @foostan did the components get placed on the footprints correctly?

**Comment by foostan** [comment]
Yes, of course.

**Comment by marleydepew** [comment]
Changing the designators to uppercase resolves the error message. The orientation of some parts still needs to be corrected in JLCPCB
