### ISSUE TITLE
Does SK6812MINI-E work in Corne 2.1 Choc?

### ISSUE THREAD

**Issue by osbm** [foostan/crkbd#263]
Well, i realised i had bought the wrong version of SMD LEDs.  Before trying to solder them i wanted to ask if it is compatible.

Would it work at all?

Or must i buy the SK6812MINI also?

**Comment by foostan** [comment]
SK6812MINI-E is not compatible with SK6812MINI.

**Comment by osbm** [comment]
I am ordering SK6812MINI 3535 (3.5 mm) Correct?

**Comment by foostan** [comment]
yes
