### ISSUE TITLE
Is it possible to use ProMicro NRF52840 or ProMicro RP2040?

### ISSUE THREAD

**Issue by angelosne** [foostan/crkbd#268]
Hello,
I bought those two proMircro alternatives knockoffs from aliexpress.

Is it possible to make it work with this keyboard? If yes what is the workflow I should follow to have a working firmware?

Sorry if question is trivial but I am quite new.

**Comment by keyboard-magpie** [comment]
They will probably work, the nrf52840 with ZMK firmware, and the pro micro rp2040 with QMK firmware.

Getting started with those firmwares is well documented, both firmwares have excellent documentation websites - https://zmk.dev/ and https://docs.qmk.fm/.

Using issues is not the best for new user support nowadays- conversational support is much easier on Discord as mentioned above. https://discord.gg/A2DN7468 for ZMK, https://discord.gg/s4gDDPUT for QMK.

**Comment by angelosne** [comment]
Thank you very much I will read those!
