### ISSUE TITLE
Keycaps In Readme

### ISSUE THREAD

**Issue by rjhilgefort** [foostan/crkbd#37]
Sorry to reach out via an issue, but I was wonder what the keycaps are in this picture and where I might be able to find them. I have a CRKBD on order and looking to flesh it out with switches and caps. Thanks in advance!

![image](https://user-images.githubusercontent.com/2034823/69455718-36f27880-0d26-11ea-8d5a-e90fa4de7576.png)

**Comment by l4u** [comment]
Probably https://make.dmm.com/item/1012817/
Related: https://github.com/foostan/crkbd/issues/13

**Comment by rjhilgefort** [comment]
Thanks @l4u , trying to order off the Japanese site and not having any luck. If anyone knows how to get em, please tag me!
