### ISSUE TITLE
How can I diy Logo easy?

### ISSUE THREAD

**Issue by liangzhaoliang95** [foostan/crkbd#46]
How can I diy Logo easy?

**Comment by benoittgt** [comment]
You mean the logo on the PCB? or LCD?

**Comment by liangzhaoliang95** [comment]
LCD LOGO, I hava solved it now ,but i think qmk should provide a simple tool to change the logo.

**Comment by benoittgt** [comment]
Out of thread: I did similar changes on ergodox: https://github.com/benoittgt/controller/tree/ergodox-miami-theme

![](https://raw.githubusercontent.com/benoittgt/controller/ergodox-miami-theme/ergdox_photo_1.jpg)

**Comment by liangzhaoliang95** [comment]
![image](https://user-images.githubusercontent.com/34703350/79064473-eb903500-7cdb-11ea-8d15-fcacf0c67a6f.png)
my keybord is crkbd

**Comment by benoittgt** [comment]
Congrats. It's beautiful! 🙌🏻

**Comment by foostan** [comment]
Oh, sorry for late return message.
@benoittgt Thank you for helping 🙏

**Comment by joric** [comment]
@liangzhaoliang95 https://github.com/joric/qle
