### ISSUE TITLE
Led broken PCB track

### ISSUE THREAD

**Issue by DLBrallan** [foostan/crkbd#69]
Hello:
I accidentally broke led track # 3 of my corne keyboard pcb so now it only lights 2 LEDs.
is there a way i can bypass led # 3 and make a kind of bridge between # 2 and # 4?
I tried to connect the DOUT of led # 2 with the DIN of led # 4 but it didn't work.
![unnamed](https://user-images.githubusercontent.com/33631753/95890940-43fec880-0d39-11eb-902b-66df89d1e0db.jpg)

my pcb is a `Corne Classic v2.0`

**Comment by keyboard-magpie** [comment]
Head on over to Foostan's discord server and we can talk you through a fix https://discord.gg/8tmn7p

**Comment by Andr3sM12** [comment]
hi i deed link to discord
