### ISSUE TITLE
Corne light purple keycaps

### ISSUE THREAD

**Issue by fidelcoria-aa** [foostan/crkbd#71]
What keycap set is that on the corne light (or is it corne cherry?) 

![](https://user-images.githubusercontent.com/736191/69654854-d615c800-10b8-11ea-8903-ebf019d7b125.png)

**Comment by carbncl** [comment]
https://drop.com/buy/massdrop-x-mito-canvas-xda-custom-keycap-set

**Comment by fidelcoria-aa** [comment]
Thanks!
