### ISSUE TITLE
Where to buy this keyboards?

### ISSUE THREAD

**Issue by juanpumpkinpie** [foostan/crkbd#88]
Do you know online websites specially availables for Europe like poland?

**Comment by keyboard-magpie** [comment]
https://keycapsss.com/
https://mechboards.co.uk/
Possibly https://pohjola.works/ soon

**Comment by juanpumpkinpie** [comment]
Do you know anothers websites or stocks? already all there in sold

**Comment by keyboard-magpie** [comment]
I forgot https://splitkb.com/products/corne-cherry-pcb-kit

**Comment by foostan** [comment]
It’s not an issue for the keyboard. Please check my discord channel and ask it. https://discord.gg/sBT3yHQK
