### ISSUE TITLE
Corne Chocolate Top Plate drill layer vs outline issue

### ISSUE THREAD

**Issue by yourfate** [foostan/crkbd#95]
I'm about to have PCBs and plates for the corne chocolate produced by JLC, and I sent them the gerber files from the release page here: 

https://github.com/foostan/crkbd/releases/tag/corne-chocolate-v2.1.0

Now I got the reply that there are cutouts in the drill layer that get cut off by the outline layer, see JLC email here:

```
Hi Sir,

Well got your order with many thanks~

Sorry to bother you, but there is an issue that we want to confirm with you before proceeding.


As shown below, the slots on the drill layer will be cut off by the slots on the board outline layer,

is it normal to cut them out per the board outline layer as non-plated slots?


Your early reply will be highly appreciated!

Thank you so much!


```

![unnamed](https://user-images.githubusercontent.com/47528796/110085460-6a2d0f80-7d91-11eb-907c-687f47882882.png)

I have for now instructed them to just cut it at the outline as they suggested. We'll see how it turns out.

**Comment by martinmunk** [comment]
Hi @yourfate 
I'm considering trying my luck with making a Choch version as well, and maybe also use JLC.
Did you end up getting the issue resolved?

**Comment by yourfate** [comment]
Hi @martinmunk, sorry for now following up on this issue.

Yes, they delivered the plates and they worked fine. You can see the result here:
![26550685bf4d7e2aec0b8c7f787fc672](https://user-images.githubusercontent.com/47528796/134386532-95fce7c0-67ae-40fb-858a-d5a5d0e90846.jpeg)

I would recommend using thinner PCB for the plates than I did, as 1.6mm is too thick for the switches' clamps to reach below. It works, but it would be neater using 1.2mm.

Side note: You can specify "Remove Order Number" at JLC, I forgot to do that, and now have order numbers on my plates and PCBs.

**Comment by pavel-rakhmanov** [comment]
Also faced with this issue while ordering corne-chocolate-v2.1.0 plates from JLC PCB but with a slightly different wording:

> As shown below, for all square slots we can only make them non-plated, is it ok？

![image](https://user-images.githubusercontent.com/22203119/143613440-15c78acb-b0b9-4b9d-9674-ddda6f7da647.png)
![image](https://user-images.githubusercontent.com/22203119/143613446-0961b18d-aee2-43fe-a81f-115ac8cc6b14.png)

**Comment by saeedb3r** [comment]
Hello everyone
I am currently in the process of building a corn chocolate keyboard, and I have received a message from the PCB manufacturer regarding the top layer. I apologize for my lack of knowledge on the subject, but I was wondering if you could kindly help me understand what is required and how to respond to the manufacturer's message. Your expertise and guidance would be greatly appreciated.

-----------------------------------
our engineer has reviewed your file and order detail, here are questions to confirm :
1.For the square slot, should we produce as plated-slot? 
2.For the slot size of drill layer, which is inconsistent with the Edge-cut layer, should we produce according to Edge-cut layer  or drill layer ?
-----------------------------------

![Pic 1](https://user-images.githubusercontent.com/35917915/208233879-5833c07a-f666-4afb-a955-084cc5b82747.png)
