### ISSUE TITLE
LEDs numeration

### ISSUE THREAD

**Issue by andrsdt** [foostan/crkbd#96]
I've been building a Corne keyboard recently and I've really enjoyed it. However, I was a bit confused by the underglow LED numeration on the Corne cherry v3.0.1 PCB. For instance, the left PCB looks like this:

![image](https://user-images.githubusercontent.com/53608787/111086486-975d8880-851c-11eb-9af6-da08591efc9c.png)

The blue numbers are, if i'm not wrong, the actual order of the WS2812 DIN-DOUT connections, being the first one the LED3 which is the closest one to the microcontroller. In my first build I soldered the LED1 expecting that it would be the first one to light up, only to find out after some desolders that the order was LED3-2-1-4-5-6.

I thought that it might be a good idea to number the LEDs after the order in which they should be installed, as shown on the [Corne classic build guide](https://user-images.githubusercontent.com/736191/40731604-62cee61e-646c-11e8-865f-829a48fa6be0.png).

Thanks for your attention.

**Comment by foostan** [comment]
Thank you for your comment.  I like the idea of ​​adding an order number after the part number.  I will consider it next time.
